Job/Controllers/ApplicantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Job.Controllers
{
    public class ApplicantController : JobController
    {
        // GET: Applicant
        public ActionResult Index()
        {
            ViewBag.applicants = UserService.GetListOfApplicants();
            return View(ViewBag.applicants);    
        }

        public ActionResult PdfDownload(string userId)
        {
            string TempFilePath = UserService.GetResumePath(userId);
            if (System.IO.File.Exists(TempFilePath))
            {
                var cd = new System.Net.Mime.ContentDisposition
                {
                    FileName = "Resume.pdf",
                    Inline = false,
                };
                Response.AppendHeader("Content-Disposition", cd.ToString());
                return File(TempFilePath, "application/pdf");
            }
            else
            {
                return null;
            }

        }
    }
}

Job/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobWebApi.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Login Page";
            return View();
        }
    }
}

Job/Controllers/PostJobController.cs
using Job.Services.IService;
using Job.Services.Models;
using Job.Services.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Job.Controllers
{
    public class PostJobController : Controller
    {
        private IJobService JobService;

        public PostJobController()
        {
            JobService = new JobService();
        }
        public ActionResult Index()
        {
            return View();
        }

        // POST: PostJob/Create
        [HttpPost]
        public ActionResult PostJob(PostJobDto postJobDto)
        {
            try
            {
                JobService.AddJob(postJobDto, "mo");
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                return View();
            }
        }
      
    }
}

Job/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using Job.Data.Models.Domain

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link runat="server" rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
    <link runat="server" rel="icon" href="~/favicon.ico" type="image/ico" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        @Html.ActionLink("JOBMENIA", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new
                    {
                        id = "logoutForm",
                        @class =
                    "navbar"
                    }))
                    {
                        @Html.AntiForgeryToken()

                        <ul class="nav navbar-nav ">
                            @if ((Session["Data"] as App_User)?.Role == "Employer")
                            {
                                <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                                <li>@Html.ActionLink("Post a Job", "Index", "PostJob", new { area = "" }, null)</li>
                                <li>@Html.ActionLink("Employer Dashboard", "Index", "Employer", new { area = "" }, null)</li>
                                <li>@Html.ActionLink("List of Applicants ", "Index", "Applicant", new { area = "" }, null)</li>
                            }
                            @if ((Session["Data"] as App_User)?.Role == "JobSeeker")
                            {
                                <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                                <li>@Html.ActionLink("Job Opening", "Index", "Search", new { area = "" }, null)</li>
                                <li>@Html.ActionLink("Profile", "Index", "Profile", new { area = "" }, null)</li>
                                <li>@Html.ActionLink("Job Dashboard", "Index", "JobDashboard", new { area = "" }, null)</li>

                            }
                            @if ((Session["Data"] as App_User)?.Role == "Admin")
                            {
                                <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                                <li>@Html.ActionLink("Admin", "Index", "Admin", new { area = "" }, null)</li>
                            }


                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues:
                        null,
                        htmlAttributes: new { title = "Manage" })
                            </li>
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                        </ul>
                    }
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            @Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new
                        {
                        id
                        = "registerLink"
                        })
                        </li>
                        <li>
                            @Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new
                        {
                        id =
                        "loginLink"
                        })
                        </li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - All Copy Right Reserved</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>